services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: GOOGLE_API_KEY
        value: ${RENDER_EXTERNAL_GOOGLE_API_KEY}
    pythonVersion: 3.11
